/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/odds/{outcomeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OddsReadController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streams/odds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OddsStreamController_odds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BettingController_list"];
        put?: never;
        post: operations["BettingController_place"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BettingController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bets/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BettingController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SettlementController_settle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReconciliationController_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WalletController_open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogController_list"];
        put?: never;
        post: operations["CatalogController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/responsible-gaming/daily-cap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ComplianceController_get"];
        put: operations["ComplianceController_set"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example betnext */
            service: string;
            /** @example 2026-06-16T00:00:00.000Z */
            timestamp: string;
        };
        CurrentOddsDto: {
            /** @example lol-finale-a */
            outcomeId: string;
            /** @example 2 */
            odds: number;
        };
        OddsLiveEventDto: {
            /** @example lol-finale-a */
            outcomeId: string;
            /** @example 2.35 */
            odds: number;
        };
        PlaceBetRequest: {
            /** @example demo-player */
            userId: string;
            /** @example lol-finale-a */
            outcomeId: string;
            /**
             * @description Mise (strictement positive)
             * @example 20
             */
            stake: number;
        };
        PlaceBetResponse: {
            /** @example 3f9c0b2e-... */
            betId: string;
            /**
             * @description Cote figée à la pose
             * @example 2
             */
            lockedOdds: number;
            /** @example 40 */
            potentialGain: number;
            /**
             * @description Cote d'ouverture (read-model froid)
             * @example true
             */
            pricingProvisional?: boolean;
        };
        BetViewDto: {
            betId: string;
            /** @example demo-player */
            userId: string;
            /** @example lol-finale-a */
            outcomeId: string;
            /** @example 20 */
            stake: number;
            /** @example 2 */
            lockedOdds: number;
            /** @example 40 */
            potentialGain: number;
            /**
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "WON" | "LOST" | "VOID" | "COMPENSATING" | "REFUNDED";
        };
        BetEventDto: {
            /** @example 1 */
            seq: number;
            /**
             * @example BetPlaced
             * @enum {string}
             */
            type: "BetPlaced" | "BetWon" | "BetLost" | "BetVoided";
            /** @example 2026-06-16T10:00:00.000Z */
            occurredAt: string;
        };
        SettleMarketRequest: {
            /**
             * @example [
             *       "lol-finale-a",
             *       "lol-finale-b",
             *       "lol-finale-draw"
             *     ]
             */
            outcomes: string[];
            /** @example lol-finale-a */
            winningOutcomeId?: string | null;
            /**
             * @description true = annulation (remboursement)
             * @example false
             */
            voided?: boolean;
            /** @example WINNING_OUTCOME */
            strategyKey?: string;
        };
        SettleMarketResultDto: {
            /** @example 2 */
            settled: number;
            /** @example 0 */
            failed: number;
            /** @example 1 */
            won: number;
            /** @example 1 */
            lost: number;
            /** @example 0 */
            voided: number;
            /** @example [] */
            failedBetIds: string[];
        };
        WalletDriftDto: {
            /** @example demo-player */
            userId: string;
            /**
             * @description Σ(ledger) = solde attendu (autoritaire)
             * @example 80
             */
            expectedBalance: number;
            /**
             * @description wallets.balance (stocké)
             * @example 130
             */
            actualBalance: number;
            /**
             * @description actual − expected (signé)
             * @example 50
             */
            difference: number;
        };
        ReconciliationReportDto: {
            /** @example 2026-06-16T10:00:00.000Z */
            checkedAt: string;
            /** @example 3 */
            walletsChecked: number;
            /**
             * @description true si aucun écart détecté
             * @example true
             */
            balanced: boolean;
            /** @description wallets en dérive (vide si balanced) */
            drifts: components["schemas"]["WalletDriftDto"][];
        };
        OpenWalletRequest: {
            /** @example demo-player */
            userId: string;
            /**
             * @description Solde d'ouverture (>= 0)
             * @example 100
             */
            openingBalance: number;
        };
        OpenWalletResultDto: {
            /** @example demo-player */
            userId: string;
            /**
             * @description false si le wallet existait déjà (idempotent)
             * @example true
             */
            opened: boolean;
        };
        OutcomeDto: {
            /** @example lol-finale-a */
            id: string;
            /** @example Victoire Team A */
            label: string;
        };
        MarketDto: {
            /** @example mkt-lol-finale */
            id: string;
            /** @example BetNext Major — Team A vs Team B */
            name: string;
            /** @example LoL */
            game: string;
            outcomes: components["schemas"]["OutcomeDto"][];
        };
        CreateMarketRequest: {
            /** @example CS Major — NaVi vs Vitality */
            name: string;
            /** @example CS2 */
            game: string;
            /**
             * @example [
             *       "Victoire NaVi",
             *       "Victoire Vitality"
             *     ]
             */
            outcomes: string[];
        };
        DailyCapDto: {
            /** @example demo-player */
            userId: string;
            /**
             * @description null si aucun plafond défini
             * @example 50
             */
            dailyCap: number | null;
        };
        SetDailyCapRequest: {
            /** @example demo-player */
            userId: string;
            /**
             * @description Plafond quotidien (> 0)
             * @example 50
             */
            cap: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service vivant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    OddsReadController_current: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outcomeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cote courante (read-model) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentOddsDto"];
                };
            };
            /** @description Read-model froid : aucune cote encore projetée */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OddsStreamController_odds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flux SSE (text/event-stream) : un message par MAJ ; data = OddsLiveEventDto (JSON). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["OddsLiveEventDto"];
                };
            };
        };
    };
    BettingController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des paris (non scopée — voir dette Identity) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetViewDto"][];
                };
            };
        };
    };
    BettingController_place: {
        parameters: {
            query?: never;
            header: {
                /** @description Clé par tentative, réutilisée au retry HTTP (anti double-débit). */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceBetRequest"];
            };
        };
        responses: {
            /** @description Pari posé (cote figée) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceBetResponse"];
                };
            };
            /** @description Même Idempotency-Key réutilisée avec un corps différent */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BettingController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetViewDto"];
                };
            };
            /** @description Pari introuvable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BettingController_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline du pari (journal append-only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetEventDto"][];
                };
            };
        };
    };
    SettlementController_settle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettleMarketRequest"];
            };
        };
        responses: {
            /** @description Règlement effectué (comptes par statut) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettleMarketResultDto"];
                };
            };
            /** @description outcomes vide, ou winningOutcomeId manquant sans voided */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReconciliationController_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rapport de réconciliation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationReportDto"];
                };
            };
        };
    };
    WalletController_open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenWalletRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenWalletResultDto"];
                };
            };
            /** @description Corps invalide (userId/openingBalance) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Solde d'ouverture invalide (doit être >= 0) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marchés ouverts (modèle N-issues) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDto"][];
                };
            };
        };
    };
    CatalogController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMarketRequest"];
            };
        };
        responses: {
            /** @description Marché créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDto"];
                };
            };
            /** @description Corps invalide (name/game/outcomes) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Marché invalide (≥ 2 issues requises) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ComplianceController_get: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCapDto"];
                };
            };
            /** @description query userId manquant */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ComplianceController_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDailyCapRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCapDto"];
                };
            };
            /** @description Corps invalide (userId/cap) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plafond invalide (doit être > 0) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
